a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
        (
            '..\\.venv\\Lib\\site-packages\\vgamepad\\win\\vigem\\client\\x64\\ViGEmClient.dll',
            'vgamepad/win/vigem/client/x64',
        )
    ],
    datas=[
        ('baits.json', '.'),
        ('icon.ico', '.'),
        ('ui', 'ui'),
        ('sounds', 'sounds'),
    ],
    hiddenimports=[
        'PySide6.QtSvg',
        'requests',
        'urllib3',
        'certifi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebEngineQuick',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtQuick3D',
        'PySide6.Qt3DCore',
        'PySide6.Qt3DRender',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DAnimation',
        'PySide6.Qt3DExtras',
        'PySide6.Qt3DLogic',
        'PySide6.QtNetwork',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtPdf',
        'PySide6.QtPdfWidgets',
        'PySide6.QtCharts',
        'PySide6.QtDataVisualization',
        'PySide6.QtWebSockets',
        'PySide6.QtBluetooth',
        'PySide6.QtPositioning',
        'PySide6.QtLocation',
        'PySide6.QtSql',
        'PySide6.QtTest',
        'PySide6.QtXml',
        'PySide6.QtDesigner',
        'PySide6.QtHelp',
        'PySide6.QtOpenGL',
        'PySide6.QtPrintSupport',
        'PySide6.QtConcurrent',

        'tkinter',
        'unittest',
        'pydoc',
        'doctest',
        'pytest',
        'numpy.tests',
        'numpy.f2py',
        'numpy.distutils',
        'cv2',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(
    a.pure
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Sea Angler Assist',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)